apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    type: mks
  name: mks-test-ha
  project: defaultproject
spec:
  blueprint:
    name: nginx
    version: v1
  config:
    autoApproveNodes: true
    dedicatedControlPlane: true
    highAvailability: true
    kubernetesVersion: v1.34.1
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: aravind-mks-ha1
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.12
      roles:
      - ControlPlane
      ssh:
        ipAddress: 161.153.28.133
        port: "22"
        privateKeyPath: /Users/immareddy/Downloads/ssh-key-2026-01-15.key
        username: ubuntu
    - arch: amd64
      hostname: aravind-mks-ha2
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.247
      roles:
      - ControlPlane
      ssh:
        ipAddress: 137.131.15.5
        port: "22"
        privateKeyPath: /Users/immareddy/Downloads/ssh-key-2026-01-15.key
        username: ubuntu
    - arch: amd64
      hostname: aravind-mks-ha3
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.61
      roles:
      - ControlPlane
      ssh:
        ipAddress: 161.153.124.80
        port: "22"
        privateKeyPath: /Users/immareddy/Downloads/ssh-key-2026-01-15.key
        username: ubuntu
    - arch: amd64
      hostname: aravind-mks-ha4
      operatingSystem: Ubuntu24.04
      privateIP: 10.0.0.56
      roles:
      - Worker
      ssh:
        ipAddress: 161.153.3.54
        port: "22"
        privateKeyPath: /Users/immareddy/Downloads/ssh-key-2026-01-15.key
        username: ubuntu
  type: mks
