apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAjkg/KT1Ug5LQAwc9epYqgz6b3P2VvQqpCOtDDW/KggQSBrZH2wuTfYka9vZxmMCCDw8Rt0r6NhKOFmAREpoA+Rcz2y6cmLxGBPneUhLjLtr/0spyMZZql2r+N0pq3IsF2XPWhn65nwQOPUIEEdgey15CuFiDK7rFpU/sOcgkvCKdDS9PXjyhJWoeDGHDb1j68J+NWyBefPfBm8WdU5JHToSKRkHnPV+0tLiLP7KvVNSofkx4cSlDsb1UfHrtKT51wcfBM+6jed0e01pqxn864Rwgh9gkAqYY8wWE0kJLvZXXB/hI/siE3kkOcMKg4Sj3SI35QesCpmALmjwWlB21Jf7TdQutcNmv+3ERF0HJM0aSlVHWbkrFNcHtvKf0hQFQ7+ECNo5goag4kroGZqUz6g/OXUI9quYg=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-git-repo
      namespace: default

