apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-oci-repo-244369607
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB3XcmDftoyFb+gFmbPybFQrq/ekLtkJW4oasiyVCMxqVXlza7TfTcE1KDWLW2LptR1jD2w4kHtlrWTMWTXnMcc0IroDc/BQ55lYCGieAfUBiEmQYEHyxSElV3JNfpTsr6c96hnlUkU1lQrJEjut2r1VM2WxxSCm/42ggXTtMs6mEyuDRy6wKHFI5Oe6B/nBf7I39nnZLiwP7oylUHUDr95Wr0Nbrrxk4WpGM+rbPDjyNne1rC81lt8QlirWMxYvTiHJzdTkXXCIIzF7TIjcMLSsGOBNcROAoz9Yrxz+a7M7R7QUUHD5b3N1zlUy0orS5wLNmA8vuDQFAI2E+EWZEF9hQO25WcQyQSgtSTadUizNfv3jVPsgErmDPDUzzzSNW2DHQ7+6L3Bd5YMbIpbGwQU
  template:
    metadata:
      creationTimestamp: null
      name: rauto-oci-repo-244369607
      namespace: default

