apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rauto-helm-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAxJp4xMY+kNfxlxOfze6GDzfhz0rlBEQW/rFwB55PeSbHGdqJra/8WtdeHcQMv4apxo69iWHggMVi83RBSRw2ycE1O3lFq3biipVGWlLrnH6vFUyMSj0rOPErHDgSDzM3CYWvotSgHyheZmuW4lL9/nvb+8x7yr14dgjCSD4WdvzShuvk0ykIdwveUZiZ4+tzMX2e+Zw/NvT389kx0bzinpq0cd2TTolNeIPQZSFspR9xnNL3X3+bvMUy4WITiHcFd9e3E191Jojv/Y9f7a4qNZvgVhJTUWi3AXCMGYlw8qJgUa9GR2DCUrVpMxBXl00/as/VYFWoNUvbL/Xfjlvrcnw1xBnu3I/nmtp4XKxNocdaGXuRHsdblxls=
  template:
    metadata:
      creationTimestamp: null
      name: rauto-helm-repo
      namespace: default

