apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: wl-ns
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: mks-test-ha
  resourceQuotas: {}
