apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  annotations:
    rafay.dev/audit_type: -||-
    rafay.dev/audit_user: onprem@rafay.co
  labels:
    rafay.dev/version: v1
  name: rauto-addon-2632377
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/rauto-addon-2632377/rauto-addon-2632377.yaml
    type: Yaml
  namespace: default-rafay
  sharing: {}
  version: v1
  versionState: active
