apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: simha-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAsLlxx9xcR8YUCPROYiTCtXFQvBAomYAAmiHL6MVTI2K5MDNJYpKyNe9yHInxunbJNfnmb7ffz8baBX/QF7kTTun/H/QxlnJ13gwCepluemyyj/kj0PCZHyMUF8CradYWoug0NGULfT2vHpXZ5gnd1+q8bKSAGhKk1t50YFmV/aRh5aCg5X0xzIVz3FBOViGeMMKUWFe7zcTqJhV4NNPq9QjASsg2gHno897INqNTUQRsnyyo7ZmUq++rDJ5w/Ugj9Au0vcX31zARQ+VU3eN65BD5X3B+0iRkhzsJi8USo5GR7qSpGOEFfLFm7CW2Gxs0BeOFuWRmfUj9wvhIHzFMLmS5hFzDlSTt27gpKjOnpJsOjq8a2nUQLfZTEbnG+7yUoTijmEHIXLO/HMlGJECT9i8IwacLCy8k=
  template:
    metadata:
      creationTimestamp: null
      name: simha-repo
      namespace: default

